#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "1 " "2 " "3 " "4 " "5 "

bspc config border_width         1
bspc config window_gap           5

bspc config normal_border_color "#16161E"
bspc config focused_border_color "#6CCFFF"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a spectacle state=floating focus=on