; ____________________ ;
[colors]
background = #16161E
background-alt = #1A1B26
foreground = #A9B1D6
primary = #7BDAF1
secondary = #8ABEB7
alert = #F7768E
disabled = #363B54

black = #111111
red = #F7768E
green = #18FFB1
orange = #FFD493
blue = #42A5F5
violet = #7353F8
pink = #F16399
white = #ffffff

; ____________________ ;
[icons]
cpu = "󰍛 "
ram = " "
storage = " "
network_connected = "󰤨 "
network_disconnected = "󰤭 "
volume = " "
muted = " "
spotify_logo = " "

; ____________________ ;
[bar/example]
width = 100%
height = 24pt
radius = 0

dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 24pt

padding-left = 0
padding-right = 1

module-margin = 0

font-0 = CaskaydiaCove Nerd Font:style=Regular:size=10;2
font-1 = Myrica P;2
font-2 = Font Awesome 6 Brands:size=11;2

modules-left = power eth xwindow ;weather
;modules-right = spotify-prev spotify spotify-next cpu memory filesystem pulseaudio date
modules-right = cpu memory pulseaudio date
modules-center = bspwm
cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = bspwm

; ____________________ ;
[module/bspwm]
type = internal/bspwm
pin-workspaces = true
enable-click = true
label-separator = ""
label-separator-padding = 1
label-empty-foreground = ${colors.disabled}
label-focused-background = ${colors.disabled}
label-focused-foreground = ${colors.foreground}
label-occupied-foreground = ${colors.foreground}

; ____________________ ;
[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
format-foreground = ${colors.disabled}
format-prefix = " "

; ____________________ ;
[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
format-mounted-prefix = ${icons.storage}
format-mounted-foreground = ${colors.black}
format-mounted-background = ${colors.orange}
format-mounted-padding = 1
format-mounted = <label-mounted>
label-mounted = %used% / %total%

; ____________________ ;
[module/pulseaudio]
type = internal/pulseaudio

label-volume = %percentage%%
format-volume-prefix = ${icons.volume}
format-volume-foreground = ${colors.white}
format-volume = <label-volume>
format-volume-background = ${colors.pink}
format-volume-padding = 1

label-muted = ${icons.muted}
label-muted-foreground = ${colors.white}
format-muted-background = ${colors.alert}
format-muted-padding = 1

; ____________________ ;
[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

; ____________________ ;
[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ${icons.cpu}
label = %percentage:2%%
format-background = ${colors.blue}
format-foreground = ${colors.white}
format-padding = 1

; ____________________ ;
[module/memory]
type = internal/memory
interval = 2
format-prefix = ${icons.ram}
format-foreground = ${colors.black}
format-background = ${colors.green}
format-padding = 1
label = %gb_used%

; ____________________ ;
[module/eth]
type = internal/network
interval = 5
label-connected = ${icons.network_connected}
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
;format-connected = ${icons.network_connected}
format-disconnected = ${icons.network_disconnected}
format-connected-foreground = ${colors.white}
format-connected-background = ${colors.violet}
format-disconnected-foreground = ${colors.white}
format-disconnected-background = ${colors.red}
format-connected-padding = 1
interface-type = wired

; ____________________ ;
[module/date]
type = internal/date
interval = 1

date = %a, %b %d %X
date-alt = %H:%M
label = %date%
format-foreground = ${colors.blue}
format-padding = 1

; ____________________ ;
[settings]
screenchange-reload = true
pseudo-transparency = true

; ____________________ ;
[module/spotify]
type = custom/script
tail = true
interval = 1
format = <label>
format-prefix = ${icons.spotify_logo}
format-prefix-foreground = ${colors.green}
format-prefix-font = 3
exec = ~/.config/polybar/scripts/spotify-status.sh
click-left = playerctl play-pause -p spotify
format-background = ${colors.black}

; ____________________ ;
[module/spotify-prev]
type = custom/script
exec = echo "❬ "
format = <label>
click-left = playerctl previous -p spotify
format-background = ${colors.black}
format-padding = 1

; ____________________ ;
[module/spotify-next]
type = custom/script
exec = echo " ❭"
format = <label>
click-left = playerctl next -p spotify
format-padding = 1
format-background = ${colors.black}

; ____________________ ;
[module/power]
type = custom/script
exec = echo " "
format = <label>
format-background = ${colors.blue}
format-foreground = ${colors.white}
format-padding = 1
click-left = ~/.config/polybar/scripts/power-menu.sh

; ____________________ ;
[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather-info.sh
tail = false
interval = 960
format-padding = 1
format-background = ${colors.black}